name: Clear All Caches and Redeploy

on:
  repository_dispatch:
    types: [sanity-content-updated]
  workflow_dispatch:

jobs:
  clear-cache-and-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Vercel Cache
        run: |
          echo "Clearing Vercel cache..."
          curl -X DELETE "https://api.vercel.com/v1/projects/${{ secrets.VERCEL_PROJECT_ID }}/domains/${{ secrets.VERCEL_DOMAIN }}/cache" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" || echo "Cache clear failed, continuing..."

      - name: Wait for cache clear
        run: sleep 15

      - name: Trigger Fresh Deployment
        run: |
          echo "Triggering deployment..."
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
          echo "✅ Cache cleared and deployment triggered!"
