name: Clear All Caches and Redeploy

on:
  repository_dispatch:
    types: [sanity-content-updated]
  workflow_dispatch:

jobs:
  clear-cache-and-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Vercel Cache
        run: |
          curl -X DELETE "https://api.vercel.com/v1/projects/${{ secrets.VERCEL_PROJECT_ID }}/domains/${{ secrets.VERCEL_DOMAIN }}/cache" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"

      - name: Purge CDN Cache (if using Cloudflare)
        if: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'

      - name: Wait for cache clear
        run: sleep 15

      - name: Trigger Fresh Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"

      - name: Deployment Status
        run: |
          echo "✅ Cache cleared and deployment triggered!"
          echo "🚀 Your site will be updated in 2-3 minutes"
